const fs = require('fs');

const CATEGORIES = [
  { id: 'all', label: 'All Products' },
  { id: 'electronics', label: 'Electronics' },
  { id: 'fashion', label: 'Fashion' },
  { id: 'beauty', label: 'Beauty' },
  { id: 'home-kitchen', label: 'Home & Kitchen' },
  { id: 'sports', label: 'Sports' },
  { id: 'travel', label: 'Travel' },
];

const SORT_OPTIONS = [
  { id: 'featured', label: 'Featured' },
  { id: 'price-asc', label: 'Price: Low to High' },
  { id: 'price-desc', label: 'Price: High to Low' },
  { id: 'rating', label: 'Highest Rated' },
  { id: 'discount', label: 'Best Discount' },
  { id: 'newest', label: 'Newest First' },
];

const PRICE_RANGES = [
  { id: 'all', label: 'Any Price', min: 0, max: Infinity },
  { id: 'under-500', label: 'Under ₹500', min: 0, max: 500 },
  { id: '500-2000', label: '₹500 – ₹2,000', min: 500, max: 2000 },
  { id: '2000-10000', label: '₹2,000 – ₹10,000', min: 2000, max: 10000 },
  { id: '10000-50000', label: '₹10,000 – ₹50,000', min: 10000, max: 50000 },
  { id: 'above-50000', label: 'Above ₹50,000', min: 50000, max: Infinity },
];

// Re-write products array completely
const products = [
  // -- Electronics (10) --
  {
    id: 'e001',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    category: 'electronics',
    price: 24990,
    originalPrice: 34990,
    discount: 29,
    rating: 4.8,
    reviews: 3412,
    description: 'Industry-leading noise cancellation with 30-hour battery life. Crystal-clear hands-free calling with multipoint connection.',
    features: ['Industry-leading noise cancellation', '30-hour battery life', 'Multipoint connection', 'Speak-to-Chat', 'Touch sensor controls'],
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 48,
    isNew: false,
  },
  {
    id: 'e002',
    name: 'Apple MacBook Air M3 13"',
    category: 'electronics',
    price: 114900,
    originalPrice: 119900,
    discount: 4,
    rating: 4.9,
    reviews: 5821,
    description: 'Supercharged by M3 chip with up to 18-hour battery life. Thin, light, and built for anything.',
    features: ['Apple M3 chip', '8GB unified memory', '256GB SSD', '18-hour battery life', '13.6" Liquid Retina display'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 12,
    isNew: false,
  },
  {
    id: 'e003',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'electronics',
    price: 109999,
    originalPrice: 129999,
    discount: 15,
    rating: 4.7,
    reviews: 2987,
    description: 'The ultimate Galaxy experience. Titanium frame, built-in S Pen, and a 200MP camera system.',
    features: ['200MP wide camera', 'Built-in S Pen', 'Titanium frame', '5000mAh battery', 'Dynamic AMOLED 2X'],
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 23,
    isNew: true,
  },
  {
    id: 'e004',
    name: 'iPad Pro 11" M4',
    category: 'electronics',
    price: 99900,
    originalPrice: 109900,
    discount: 9,
    rating: 4.8,
    reviews: 1654,
    description: 'Impossibly thin. The thinnest Apple product ever. Ultra Retina XDR OLED display with Apple M4.',
    features: ['Apple M4 chip', 'Ultra Retina XDR OLED', 'Apple Pencil Pro compatible', '10-hour battery', 'Wi-Fi 6E'],
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 7,
    isNew: true,
  },
  {
    id: 'e005',
    name: 'Bose QuietComfort Ultra Earbuds',
    category: 'electronics',
    price: 23900,
    originalPrice: 27900,
    discount: 14,
    rating: 4.6,
    reviews: 1189,
    description: 'World-class noise cancellation in a truly wireless earbud. Immersive Audio for a more spatial listening experience.',
    features: ['World-class noise cancellation', 'Immersive spatial audio', '6-hour battery', 'CustomTune technology', 'IPX4 water resistant'],
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 31,
    isNew: false,
  },
  {
    id: 'e006',
    name: 'Canon EOS R50 Mirrorless Camera',
    category: 'electronics',
    price: 64999,
    originalPrice: 74999,
    discount: 13,
    rating: 4.5,
    reviews: 876,
    description: 'A compact, lightweight mirrorless camera with 24.2MP and advanced AI-powered subject tracking.',
    features: ['24.2MP APS-C CMOS sensor', 'AI-powered subject detection', '4K 30fps video', 'Vari-angle touchscreen', 'Wi-Fi & Bluetooth'],
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 14,
    isNew: false,
  },
  {
    id: 'e007',
    name: 'Sony PlayStation 5 Console',
    category: 'electronics',
    price: 49990,
    originalPrice: 54990,
    discount: 9,
    rating: 4.9,
    reviews: 12543,
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback.',
    features: ['Ultra-high speed SSD', 'Ray Tracing', '4K-TV Gaming', 'Up to 120fps with 120Hz output', 'HDR Technology'],
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 105,
    isNew: false,
  },
  {
    id: 'e008',
    name: 'LG C3 65" 4K OLED Smart TV',
    category: 'electronics',
    price: 189990,
    originalPrice: 249990,
    discount: 24,
    rating: 4.8,
    reviews: 842,
    description: 'Advanced OLED picture quality. The a9 AI Processor Gen6 creates a picture that looks like real life.',
    features: ['OLED evo panel', 'a9 AI Processor Gen6', 'Dolby Vision & Atmos', 'WebOS 23', '120Hz refresh rate'],
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 5,
    isNew: false,
  },
  {
    id: 'e009',
    name: 'Logitech MX Master 3S Mouse',
    category: 'electronics',
    price: 9999,
    originalPrice: 10995,
    discount: 9,
    rating: 4.7,
    reviews: 4512,
    description: 'An iconic mouse remastered. Quiet Clicks and an 8K DPI track-on-glass sensor.',
    features: ['Quiet Clicks', '8000 DPI tracking', 'MagSpeed scrolling', 'Ergonomic design', 'Multi-device pairing'],
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 42,
    isNew: false,
  },
  {
    id: 'e010',
    name: 'Amazon Kindle Paperwhite',
    category: 'electronics',
    price: 13999,
    originalPrice: 13999,
    discount: 0,
    rating: 4.6,
    reviews: 9542,
    description: 'Now with a 6.8” display and thinner borders, adjustable warm light, up to 10 weeks of battery life.',
    features: ['6.8” glare-free display', 'Adjustable warm light', 'Waterproof (IPX8)', '10 weeks battery life', '16GB storage'],
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 89,
    isNew: false,
  },

  // -- Fashion (10) --
  {
    id: 'f001',
    name: 'Levi\'s 511 Slim Fit Jeans',
    category: 'fashion',
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    rating: 4.4,
    reviews: 6721,
    description: 'The iconic slim-fit jean. Sits below the waist, slim through hip and thigh, and a narrow leg opening.',
    features: ['Slim fit below waist', '99% Cotton, 1% Elastane', 'Stretch denim', '5-pocket styling', 'Machine washable'],
    image: 'https://images.unsplash.com/photo-1542272604-780c8d52a5ce?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 200,
    isNew: false,
  },
  {
    id: 'f002',
    name: 'Nike Air Max 270 Sneakers',
    category: 'fashion',
    price: 8995,
    originalPrice: 11995,
    discount: 25,
    rating: 4.6,
    reviews: 4532,
    description: 'Inspired by Air Max icons of the past, the Nike Air Max 270 delivers big, bold cushioning.',
    features: ['Max Air 270 heel unit', 'Engineered mesh upper', 'Foam midsole', 'Rubber outsole', 'Breathable design'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 87,
    isNew: false,
  },
  {
    id: 'f003',
    name: 'Tommy Hilfiger Oxford Shirt',
    category: 'fashion',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 4.3,
    reviews: 2143,
    description: 'Classic Oxford shirt with signature Tommy flag branding. A timeless wardrobe essential.',
    features: ['100% Cotton Oxford fabric', 'Regular fit', 'Button-down collar', 'Embroidered flag logo', 'Machine washable'],
    image: 'https://images.unsplash.com/photo-1596755094514-f87e32f85e23?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 145,
    isNew: false,
  },
  {
    id: 'f004',
    name: 'Adidas Ultraboost 22 Running Shoes',
    category: 'fashion',
    price: 12999,
    originalPrice: 16999,
    discount: 24,
    rating: 4.7,
    reviews: 3298,
    description: 'Premium running shoes with Boost midsole technology for incredible energy return.',
    features: ['Boost midsole technology', 'PRIMEKNIT+ upper', 'Continental rubber outsole', 'Linear Energy Push system', 'Lightweight'],
    image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 62,
    isNew: false,
  },
  {
    id: 'f005',
    name: 'Fossil Gen 6 Smartwatch',
    category: 'fashion',
    price: 18995,
    originalPrice: 24995,
    discount: 24,
    rating: 4.2,
    reviews: 987,
    description: 'Wear OS smartwatch with Snapdragon 4100+ platform, SpO2 tracking, and a stunning AMOLED display.',
    features: ['Wear OS by Google', 'Snapdragon Wear 4100+', 'Heart rate & SpO2 monitoring', '1.28" AMOLED display', 'NFC payments'],
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: false,
    stockCount: 0,
    isNew: false,
  },
  {
    id: 'f006',
    name: 'Ray-Ban Aviator Classic Sunglasses',
    category: 'fashion',
    price: 11990,
    originalPrice: 14990,
    discount: 20,
    rating: 4.8,
    reviews: 5214,
    description: 'Currently one of the most iconic sunglass models in the world. Timeless model that combines great aviator styling with exceptional quality.',
    features: ['100% UV protection', 'Metal frame', 'Classic G-15 lenses', 'Adjustable nose pads', 'Includes case'],
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 34,
    isNew: false,
  },
  {
    id: 'f007',
    name: 'Calvin Klein Leather Belt',
    category: 'fashion',
    price: 2499,
    originalPrice: 3499,
    discount: 28,
    rating: 4.5,
    reviews: 1245,
    description: 'Sleek and versatile leather belt perfect for formal or casual wear. Features a classic metal buckle.',
    features: ['100% Genuine Leather', 'Classic metal buckle', 'Adjustable fit', 'Reversible design', 'Imported'],
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 95,
    isNew: false,
  },
  {
    id: 'f008',
    name: 'Puma Suede Classic Sneakers',
    category: 'fashion',
    price: 5999,
    originalPrice: 6999,
    discount: 14,
    rating: 4.6,
    reviews: 3412,
    description: 'The most well-known and popular of all PUMA shoes. Suede upper with a classic low-top profile.',
    features: ['Suede upper', 'Rubber outsole', 'Lace closure', 'PUMA Formstrip', 'Padded collar for comfort'],
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 45,
    isNew: false,
  },
  {
    id: 'f009',
    name: 'Zara Wool Blend Coat',
    category: 'fashion',
    price: 8990,
    originalPrice: 11990,
    discount: 25,
    rating: 4.7,
    reviews: 865,
    description: 'Long coat made of a wool blend. Featuring a lapel collar, long sleeves, front flap pockets and front button fastening.',
    features: ['75% Wool, 25% Polyamide', 'Lapel collar', 'Front flap pockets', 'Button fastening', 'Dry clean only'],
    image: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 18,
    isNew: true,
  },
  {
    id: 'f010',
    name: 'Casio G-Shock Watch',
    category: 'fashion',
    price: 7995,
    originalPrice: 8995,
    discount: 11,
    rating: 4.9,
    reviews: 8921,
    description: 'The ultimate tough watch. Shock resistant and 200M water resistant. Built for extreme conditions.',
    features: ['Shock Resistant', '200 Meter Water Resistant', 'EL Backlight with Afterglow', 'Multi-function Alarm', 'Countdown Timer'],
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 112,
    isNew: false,
  },

  // -- Beauty (10) --
  {
    id: 'b001',
    name: 'Dyson Supersonic Hair Dryer',
    category: 'beauty',
    price: 31900,
    originalPrice: 38900,
    discount: 18,
    rating: 4.8,
    reviews: 2345,
    description: 'Engineered to protect hair from extreme heat damage. Fast drying with controlled airflow.',
    features: ['Intelligent heat control', 'Acoustically tuned motor', 'Magnetic attachments', '4 heat settings', 'Ionic conditioning'],
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 28,
    isNew: false,
  },
  {
    id: 'b002',
    name: 'Forest Essentials Facial Serum',
    category: 'beauty',
    price: 1995,
    originalPrice: 2495,
    discount: 20,
    rating: 4.5,
    reviews: 1876,
    description: 'Luxury Ayurvedic facial serum with 24k gold and saffron. For radiant, youthful skin.',
    features: ['24k gold infused', 'Saffron & Sandalwood', 'Ayurvedic cold-pressed base', 'Cruelty-free', 'Suitable for all skin types'],
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Luxury',
    inStock: true,
    stockCount: 54,
    isNew: false,
  },
  {
    id: 'b003',
    name: 'The Ordinary Skincare Starter Kit',
    category: 'beauty',
    price: 1499,
    originalPrice: 2099,
    discount: 29,
    rating: 4.6,
    reviews: 5432,
    description: 'Evidence-based skincare essentials. Niacinamide, Hyaluronic Acid, and AHA/BHA peeling solution.',
    features: ['Niacinamide 10% + Zinc 1%', 'Hyaluronic Acid 2% + B5', 'AHA 30% + BHA 2%', 'Cruelty-free', '30ml each'],
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Value Pack',
    inStock: true,
    stockCount: 110,
    isNew: false,
  },
  {
    id: 'b004',
    name: 'Philips IPL Hair Removal Device',
    category: 'beauty',
    price: 12990,
    originalPrice: 17990,
    discount: 28,
    rating: 4.3,
    reviews: 1654,
    description: 'Clinically proven IPL technology for permanent hair reduction at home. Gentle on all skin tones.',
    features: ['250,000 light pulses', '5 intensity settings', 'Skin tone sensor', 'Cordless', 'Visible results in 4 weeks'],
    image: 'https://images.unsplash.com/photo-1556228720-1c2a468e55cd?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 39,
    isNew: false,
  },
  {
    id: 'b005',
    name: 'MAC Ruby Woo Matte Lipstick',
    category: 'beauty',
    price: 1950,
    originalPrice: 1950,
    discount: 0,
    rating: 4.8,
    reviews: 12045,
    description: 'The iconic matte red lipstick that made MAC famous. Vivid blue-red with a completely matte finish.',
    features: ['Long-wearing, 8 hours', 'Non-feathering', 'Fade-proof', 'Matte finish', 'Highly pigmented'],
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 120,
    isNew: false,
  },
  {
    id: 'b006',
    name: 'Estée Lauder Advanced Night Repair',
    category: 'beauty',
    price: 8900,
    originalPrice: 8900,
    discount: 0,
    rating: 4.9,
    reviews: 8754,
    description: 'The UK\'s #1 serum. Fast-penetrating serum reduces the look of multiple signs of aging.',
    features: ['Chronolux™ Power Signal', 'Deep hydration', 'Anti-aging', 'Oil-free', 'Dermatologist-tested'],
    image: 'https://images.unsplash.com/photo-1571781926291-c477eb3af7dc?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 45,
    isNew: false,
  },
  {
    id: 'b007',
    name: 'Chanel No. 5 Eau de Parfum',
    category: 'beauty',
    price: 14500,
    originalPrice: 14500,
    discount: 0,
    rating: 4.7,
    reviews: 3241,
    description: 'A highly complex blend of aldehydes and florals - including rose, ylang-ylang, jasmine, lily of the valley and iris.',
    features: ['100ml spray', 'Floral aldehyde fragrance', 'Iconic minimalist bottle', 'Long lasting', 'Classic luxury'],
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Luxury',
    inStock: true,
    stockCount: 12,
    isNew: false,
  },
  {
    id: 'b008',
    name: 'Clinique Moisture Surge 100H',
    category: 'beauty',
    price: 3600,
    originalPrice: 4200,
    discount: 14,
    rating: 4.6,
    reviews: 4125,
    description: 'An oil-free gel-cream moisturizer that keeps skin hydrated even after washing your face.',
    features: ['100 hours of hydration', 'Aloe bio-ferment', 'Hyaluronic acid', 'Oil-free formula', 'For all skin types'],
    image: 'https://images.unsplash.com/photo-1611077544760-4493ceec7b6b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 68,
    isNew: false,
  },
  {
    id: 'b009',
    name: 'L\'Oréal Voluminous Lash Paradise Mascara',
    category: 'beauty',
    price: 899,
    originalPrice: 1099,
    discount: 18,
    rating: 4.5,
    reviews: 18542,
    description: 'Take your lashes to paradise. Voluptuous volume and intense length with a soft, wavy bristle brush.',
    features: ['Voluptuous volume', 'Intense length', 'Soft wavy bristle brush', 'Smudge-proof', 'Ophthalmologist tested'],
    image: 'https://images.unsplash.com/photo-1512496015851-a1c848cb32f3?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 240,
    isNew: false,
  },
  {
    id: 'b010',
    name: 'Kiehl\'s Ultra Facial Cream',
    category: 'beauty',
    price: 2950,
    originalPrice: 3200,
    discount: 7,
    rating: 4.7,
    reviews: 5124,
    description: 'A 24-hour daily face moisturizer that provides continuous hydration for softer, smoother, and visibly healthier-looking skin.',
    features: ['24-hour hydration', 'Contains Glacial Glycoprotein', 'Olive-derived Squalane', 'Lightweight texture', 'Paraben-free'],
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 77,
    isNew: false,
  },

  // -- Home & Kitchen (10) --
  {
    id: 'h001',
    name: 'Instant Pot Duo 7-in-1 Pressure Cooker',
    category: 'home-kitchen',
    price: 7499,
    originalPrice: 9999,
    discount: 25,
    rating: 4.7,
    reviews: 8932,
    description: '7-in-1 multi-use programmable pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and warmer.',
    features: ['7 cooking functions', '6-quart capacity', '13 smart programs', 'Delay start up to 24 hours', 'Keep warm function'],
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 156,
    isNew: false,
  },
  {
    id: 'h002',
    name: 'Dyson V15 Detect Cordless Vacuum',
    category: 'home-kitchen',
    price: 52900,
    originalPrice: 62900,
    discount: 16,
    rating: 4.8,
    reviews: 2107,
    description: 'Laser reveals invisible dust. Precisely counts and sizes particles with piezo sensor.',
    features: ['Laser Slim Fluffy head', 'Piezo sensor counts dust', 'HEPA filtration', '60-minute run time', 'LCD screen display'],
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 19,
    isNew: false,
  },
  {
    id: 'h003',
    name: 'Philips Air Fryer XXL HD9860',
    category: 'home-kitchen',
    price: 12995,
    originalPrice: 16995,
    discount: 24,
    rating: 4.5,
    reviews: 4231,
    description: 'Largest Philips Air Fryer. Fry, bake, grill, and roast with up to 90% less fat.',
    features: ['7.2L XXL capacity', 'Smart Sensing technology', 'Twin TurboStar tech', 'NutriU app connectivity', 'Dishwasher safe'],
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 73,
    isNew: false,
  },
  {
    id: 'h004',
    name: 'IKEA KALLAX Shelf Unit',
    category: 'home-kitchen',
    price: 8999,
    originalPrice: 10999,
    discount: 18,
    rating: 4.4,
    reviews: 3102,
    description: 'Versatile shelving unit that can be used as a room divider, sideboard, or bookcase.',
    features: ['4x4 cube design', 'Compatible with inserts', 'Wall mountable', 'Weight capacity: 13 kg/shelf', 'Particleboard construction'],
    image: 'https://images.unsplash.com/photo-1595514535415-00dbf83c135e?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 42,
    isNew: false,
  },
  {
    id: 'h005',
    name: 'Nespresso Vertuo Next Coffee Machine',
    category: 'home-kitchen',
    price: 13990,
    originalPrice: 17990,
    discount: 22,
    rating: 4.6,
    reviews: 1543,
    description: 'Brew 5 cup sizes from espresso to Alto XL. Centrifusion technology for perfect coffee every time.',
    features: ['5 cup sizes', 'Centrifusion extraction', 'Automatic capsule recognition', '30-second heat-up', 'Wi-Fi & Bluetooth'],
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 34,
    isNew: true,
  },
  {
    id: 'h006',
    name: 'KitchenAid Artisan Stand Mixer',
    category: 'home-kitchen',
    price: 45990,
    originalPrice: 49990,
    discount: 8,
    rating: 4.9,
    reviews: 14502,
    description: 'Make up to 9 dozen cookies in a single batch with the KitchenAid Artisan Series 5 Quart Tilt-Head Stand Mixer.',
    features: ['5 Quart Stainless Steel Bowl', '10 Speeds', 'Tilt-Head Design', 'Includes flat beater, dough hook, wire whip', 'Over 10 available attachments'],
    image: 'https://images.unsplash.com/photo-1591324535489-9c78ea9a4e44?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 15,
    isNew: false,
  },
  {
    id: 'h007',
    name: 'iRobot Roomba j7+ Robot Vacuum',
    category: 'home-kitchen',
    price: 64900,
    originalPrice: 74900,
    discount: 13,
    rating: 4.6,
    reviews: 3211,
    description: 'Identifies and avoids obstacles like pet waste and charging cords. Empties itself into the Clean Base.',
    features: ['PrecisionVision Navigation', 'Automatic Dirt Disposal', 'Smart Mapping', 'Voice Assistant Integration', 'Pet owner recommended'],
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 8,
    isNew: false,
  },
  {
    id: 'h008',
    name: 'Le Creuset Enameled Cast Iron Dutch Oven',
    category: 'home-kitchen',
    price: 28900,
    originalPrice: 32900,
    discount: 12,
    rating: 4.9,
    reviews: 5621,
    description: 'The iconic French oven is indispensable in the kitchens of home cooks and professional chefs alike.',
    features: ['Enameled cast iron', 'Excellent heat distribution', 'Chip-resistant enamel', 'Oven safe up to 500°F', 'Lifetime warranty'],
    image: 'https://images.unsplash.com/photo-1584269600519-112d071b26e6?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Luxury',
    inStock: true,
    stockCount: 22,
    isNew: false,
  },
  {
    id: 'h009',
    name: 'Vitamix 5200 Professional-Grade Blender',
    category: 'home-kitchen',
    price: 42999,
    originalPrice: 49999,
    discount: 14,
    rating: 4.8,
    reviews: 7842,
    description: 'The classic blending machine that professionals trust. Can blend everything from smoothies to hot soups.',
    features: ['Variable Speed Control', '64-ounce container', 'Aircraft-grade stainless steel blades', 'Self-Cleaning', '7-year full warranty'],
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 36,
    isNew: false,
  },
  {
    id: 'h010',
    name: 'Weber Spirit II E-210 Gas Grill',
    category: 'home-kitchen',
    price: 34990,
    originalPrice: 39990,
    discount: 12,
    rating: 4.7,
    reviews: 4210,
    description: 'Step up your grilling game with the Spirit II E-210 gas grill. Features two burners and a spacious cooking area.',
    features: ['GS4 grilling system', 'Two stainless steel burners', 'Porcelain-enameled cast-iron grates', 'Built-in lid thermometer', 'Open cart design'],
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 11,
    isNew: false,
  },

  // -- Sports (10) --
  {
    id: 's001',
    name: 'Garmin Forerunner 265 GPS Watch',
    category: 'sports',
    price: 34999,
    originalPrice: 42999,
    discount: 19,
    rating: 4.7,
    reviews: 1876,
    description: 'Advanced running metrics with AMOLED display. Training Readiness and HRV Status for smarter training.',
    features: ['AMOLED touchscreen', 'Training Readiness score', 'HRV Status monitoring', 'Race Predictor & Pacer', 'Built-in GPS'],
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 27,
    isNew: false,
  },
  {
    id: 's002',
    name: 'Yonex Arcsaber 11 Pro Badminton Racket',
    category: 'sports',
    price: 9990,
    originalPrice: 12990,
    discount: 23,
    rating: 4.6,
    reviews: 987,
    description: 'Ultra-precision control racket used by World Champions. Rotational Generator System for quick recovery.',
    features: ['Rotational Generator System', 'Graphite frame with Nanometric', '4U weight class', 'G5 grip size', 'Head heavy balance'],
    image: 'https://images.unsplash.com/photo-1622279457486-640c4cb686ac?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Pro',
    inStock: true,
    stockCount: 18,
    isNew: false,
  },
  {
    id: 's003',
    name: 'Decathlon Domyos Yoga Mat',
    category: 'sports',
    price: 799,
    originalPrice: 1099,
    discount: 27,
    rating: 4.4,
    reviews: 5621,
    description: 'Non-slip 5mm yoga mat with carry strap. Ideal for all styles of yoga and floor exercises.',
    features: ['5mm thick support', 'Non-slip texture', 'NBR foam material', '183cm × 61cm dimensions', 'Includes carry strap'],
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Value',
    inStock: true,
    stockCount: 320,
    isNew: false,
  },
  {
    id: 's004',
    name: 'Fitbit Charge 6 Fitness Tracker',
    category: 'sports',
    price: 14999,
    originalPrice: 18999,
    discount: 21,
    rating: 4.5,
    reviews: 2341,
    description: 'Advanced health tracking with Google Maps, YouTube Music, and Google Wallet built in.',
    features: ['Built-in GPS', 'Google apps integration', '40+ exercise modes', '7-day battery life', 'EDA sensor for stress'],
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 51,
    isNew: true,
  },
  {
    id: 's005',
    name: 'Boldfit Adjustable Dumbbell Set',
    category: 'sports',
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    rating: 4.3,
    reviews: 3214,
    description: 'Space-saving adjustable dumbbell pair. Replaces 15 sets of weights in one compact design.',
    features: ['Adjustable 2.5kg to 25kg', 'Replaces 15 dumbbell sets', 'Quick weight adjustment', 'Anti-slip handle', 'Compact storage'],
    image: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 88,
    isNew: false,
  },
  {
    id: 's006',
    name: 'Spalding NBA Official Indoor Basketball',
    category: 'sports',
    price: 3499,
    originalPrice: 4500,
    discount: 22,
    rating: 4.8,
    reviews: 2154,
    description: 'The official ball of the NBA. Features a full-grain leather cover that turns butter-soft once broken in.',
    features: ['Official NBA size and weight', 'Full-grain leather cover', 'Designed for indoor play only', 'Shipped inflated', 'Exceptional grip'],
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 154,
    isNew: false,
  },
  {
    id: 's007',
    name: 'Speedo Vanquisher 2.0 Swim Goggles',
    category: 'sports',
    price: 1899,
    originalPrice: 2299,
    discount: 17,
    rating: 4.6,
    reviews: 8452,
    description: 'One of the most popular competitive racing goggles. Offers a sleek, snug, inner-eye fit.',
    features: ['Anti-fog coating', 'UV protection', 'Interchangeable nose pieces', 'Silicone double headstrap', 'PVC and Latex free'],
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 210,
    isNew: false,
  },
  {
    id: 's008',
    name: 'Callaway Strata Complete Golf Set',
    category: 'sports',
    price: 34900,
    originalPrice: 39900,
    discount: 13,
    rating: 4.7,
    reviews: 1245,
    description: 'Designed to give you maximum performance right out of the box for more confidence from tee-to-green.',
    features: ['12-Piece Set', '460cc Forged Driver', 'Fairway wood & hybrid', 'Irons/Wedges (6-PW)', 'Stand bag included'],
    image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 14,
    isNew: false,
  },
  {
    id: 's009',
    name: 'Nike Dri-FIT Men\'s Training T-Shirt',
    category: 'sports',
    price: 1495,
    originalPrice: 1995,
    discount: 25,
    rating: 4.5,
    reviews: 3210,
    description: 'The Nike Dri-FIT T-Shirt delivers a soft feel, sweat-wicking performance and great range of motion.',
    features: ['Dri-FIT Technology', 'Standard fit', 'Ribbed crew neck', '100% polyester', 'Machine washable'],
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 156,
    isNew: false,
  },
  {
    id: 's010',
    name: 'Theragun Pro Percussive Massager',
    category: 'sports',
    price: 54900,
    originalPrice: 59900,
    discount: 8,
    rating: 4.9,
    reviews: 4122,
    description: 'Powerful, quiet, and commercial-grade. The professional smart percussive therapy device in a league of its own.',
    features: ['QuietForce Technology', 'Smart app integration', 'OLED screen', 'Customizable speed range', '2 swappable batteries (150 min each)'],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 22,
    isNew: false,
  },

  // -- Travel (10) --
  {
    id: 't001',
    name: 'Samsonite Proxis Spinner 75cm Luggage',
    category: 'travel',
    price: 18995,
    originalPrice: 26995,
    discount: 30,
    rating: 4.7,
    reviews: 1543,
    description: 'Ultra-lightweight polycarbonate shell with TSA-approved lock. Glides effortlessly on 4 double spinner wheels.',
    features: ['Polycarbonate shell', 'TSA-approved lock', '4 double spinner wheels', 'Expandable (15% more capacity)', 'USB port on main compartment'],
    image: 'https://images.unsplash.com/photo-1565026057447-bc90829cebba?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 23,
    isNew: false,
  },
  {
    id: 't002',
    name: 'Osprey Farpoint 40 Travel Backpack',
    category: 'travel',
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    rating: 4.8,
    reviews: 2198,
    description: 'Cabin-sized travel pack built for the modern traveller. Panel-loading main compartment and detachable daypack.',
    features: ['40L capacity (carry-on)', 'Stowaway padded hip belt', 'Laptop compartment (up to 15")', 'Lockable zippers', 'Lifetime warranty'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Editor\'s Choice',
    inStock: true,
    stockCount: 41,
    isNew: false,
  },
  {
    id: 't003',
    name: 'Anker PowerCore 26800 Portable Charger',
    category: 'travel',
    price: 3999,
    originalPrice: 5499,
    discount: 27,
    rating: 4.6,
    reviews: 7832,
    description: '26800mAh power bank with triple USB-A ports and USB-C. Charge multiple devices simultaneously.',
    features: ['26800mAh capacity', 'Charges iPhone 15 6.5 times', 'Triple USB-A ports', 'PowerIQ 3.0 fast charge', 'Airline travel safe'],
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Rated',
    inStock: true,
    stockCount: 197,
    isNew: false,
  },
  {
    id: 't004',
    name: 'DJI Mini 4 Pro Drone',
    category: 'travel',
    price: 74999,
    originalPrice: 84999,
    discount: 12,
    rating: 4.8,
    reviews: 1023,
    description: 'Under 249g, no registration required. 4K/60fps video, omnidirectional obstacle sensing.',
    features: ['4K/60fps HDR video', '48MP RAW photos', 'Omnidirectional obstacle sensing', '34-minute flight time', '20km video transmission'],
    image: 'https://images.unsplash.com/photo-1507582020474-9a35e7d65466?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Premium',
    inStock: true,
    stockCount: 9,
    isNew: true,
  },
  {
    id: 't005',
    name: 'Travelpro Maxlite 5 Carry-On',
    category: 'travel',
    price: 8999,
    originalPrice: 12999,
    discount: 31,
    rating: 4.5,
    reviews: 2876,
    description: 'Ultra-lightweight carry-on with built-in USB port. Fits in all major airline overhead bins.',
    features: ['2.6kg ultra-lightweight', 'Built-in USB-A port', 'Patented PowerScope handle', '8-spinner wheel system', 'Airline-approved size'],
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Sale',
    inStock: true,
    stockCount: 66,
    isNew: false,
  },
  {
    id: 't006',
    name: 'Bose Noise Cancelling Headphones 700',
    category: 'travel',
    price: 29900,
    originalPrice: 34500,
    discount: 13,
    rating: 4.7,
    reviews: 5412,
    description: 'Critically acclaimed noise cancelling headphones with unrivaled voice pickup. Perfect for long flights.',
    features: ['11 levels of noise cancelling', 'Astounding sound quality', 'Unrivaled voice pickup', '20-hour battery life', 'Alexa and Google Assistant'],
    image: 'https://images.unsplash.com/photo-1546435770-a3e426fac332?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Top Pick',
    inStock: true,
    stockCount: 38,
    isNew: false,
  },
  {
    id: 't007',
    name: 'Victorinox Swiss Army Huntsman Knife',
    category: 'travel',
    price: 3590,
    originalPrice: 3990,
    discount: 10,
    rating: 4.9,
    reviews: 12450,
    description: 'Perfect for climbing, hiking and camping. Includes 15 functions including scissors and a wood saw.',
    features: ['15 functions', 'Stainless steel construction', 'Compact 3.6 inch size', 'Includes wood saw and scissors', 'Lifetime guarantee'],
    image: 'https://images.unsplash.com/photo-1581453904507-626ddb717f59?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Best Seller',
    inStock: true,
    stockCount: 310,
    isNew: false,
  },
  {
    id: 't008',
    name: 'Cabeau Evolution S3 Travel Pillow',
    category: 'travel',
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.5,
    reviews: 3214,
    description: 'Engineered memory foam travel pillow that attaches to airplane seats to prevent your head from falling forward.',
    features: ['Seat strap system', 'Premium memory foam', 'Washable cover', 'Compact travel case included', 'Raised side supports'],
    image: 'https://images.unsplash.com/photo-1563604044-672ce12d263b?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 145,
    isNew: false,
  },
  {
    id: 't009',
    name: 'GoPro HERO12 Black Action Camera',
    category: 'travel',
    price: 39990,
    originalPrice: 45000,
    discount: 11,
    rating: 4.8,
    reviews: 4210,
    description: 'Incredible image quality, even better HyperSmooth video stabilization and a huge boost in battery life.',
    features: ['5.3K60 video', '27MP photos', 'HyperSmooth 6.0 stabilization', 'Waterproof to 33ft', 'Dual LCD screens'],
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'New',
    inStock: true,
    stockCount: 52,
    isNew: true,
  },
  {
    id: 't010',
    name: 'Eagle Creek Pack-It Specter Cubes',
    category: 'travel',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    rating: 4.7,
    reviews: 2154,
    description: 'Ultra-lightweight packing organizers keep your luggage organized without adding extra weight.',
    features: ['Set of 3 cubes', 'Ultra-lightweight silnylon fabric', 'Water-repellent', 'Machine washable', 'Quick grab handle'],
    image: 'https://images.unsplash.com/photo-1553531580-6520e780eb15?auto=format&fit=crop&q=80&w=800&h=800',
    badge: null,
    inStock: true,
    stockCount: 89,
    isNew: false,
  }
];

function sortProducts(products, sortId) {
  const arr = [...products];
  switch (sortId) {
    case 'price-asc':
      return arr.sort((a, b) => a.price - b.price);
    case 'price-desc':
      return arr.sort((a, b) => b.price - a.price);
    case 'rating':
      return arr.sort((a, b) => b.rating - a.rating);
    case 'discount':
      return arr.sort((a, b) => b.discount - a.discount);
    case 'newest':
      return arr.sort((a, b) => (b.isNew ? 1 : 0) - (a.isNew ? 1 : 0));
    case 'featured':
    default:
      return arr;
  }
}

function filterProducts(products, { query = '', category = 'all', priceRange = 'all' }) {
  const q = query.trim().toLowerCase();
  const range = PRICE_RANGES.find((r) => r.id === priceRange) ?? PRICE_RANGES[0];

  return products.filter((p) => {
    const matchesCategory = category === 'all' || p.category === category;
    const matchesPrice = p.price >= range.min && p.price <= range.max;
    const matchesQuery =
      !q ||
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.features.some((f) => f.toLowerCase().includes(q));
    return matchesCategory && matchesPrice && matchesQuery;
  });
}

const fileContent = \`/**
 * MerchantFlow — Mock Product Catalogue
 * Local data for the Discover experience.
 * Will be consumed by AI agent in later parts.
 */

export const CATEGORIES = \${JSON.stringify(CATEGORIES, null, 2).replace(/"([^"]+)":/g, '$1:')};

export const SORT_OPTIONS = \${JSON.stringify(SORT_OPTIONS, null, 2).replace(/"([^"]+)":/g, '$1:')};

export const PRICE_RANGES = \${JSON.stringify(PRICE_RANGES, null, 2).replace(/"([^"]+)":/g, '$1:')};

/** @type {Product[]} */
export const PRODUCTS = \${JSON.stringify(products, null, 2).replace(/"([^"]+)":/g, '$1:')};

/**
 * Sort products by the given sort option.
 * @param {Product[]} products
 * @param {string} sortId
 * @returns {Product[]}
 */
export \${sortProducts.toString()}

/**
 * Filter products by search query, category, and price range.
 */
export \${filterProducts.toString()}
\`;

fs.writeFileSync('lib/products.js', fileContent, 'utf-8');
console.log('Successfully wrote 60 products to lib/products.js');
